### ISSUE TITLE
你好，我复制了你的代码在我的电脑上运行，但是准确度非常低。

### ISSUE THREAD

**Issue by zh0ngtian** [hankcs/udacity-deep-learning#1]
你好，我复制了你的代码在我的电脑上运行，但是准确度非常低，试了好几次仍旧这样。最后的神经网络的Test accuracy只能到百分之20左右，不知道原因在哪里，若能提供改进思路，万分感激！

**Comment by hankcs** [comment]
0. 如果每道题都这样，可能是TF版本的问题
0. 否则可能是我改写的问题，你可以跟我参考的代码对比一下：https://github.com/rndbrtrnd/udacity-deep-learning

**Comment by zh0ngtian** [comment]
你好，我今天上午从头看了一下，重新序列化了数据，问题就解决了。谢谢你的回复与解答，祝身体健康，生活愉快!
